export const ERROR_CODES = {
  AUTH_USER_NOT_FOUND: 'AUTH101',
  AUTH_TOKEN_EXPIRED: 'AUTH102',
  AUTH_PHONE_INVALID_FORMAT: 'AUTH201',
  AUTH_PHONE_TOO_SOON: 'AUTH202',
  AUTH_PHONE_DAILY_LIMIT: 'AUTH203',
  AUTH_PHONE_SMS_FAILED: 'AUTH204',
  MEMBER_NOT_FOUND: 'MEMBER201',
} as const;
