// public/fitness36.csv 데이터를 기반으로 생성한 정적 데이터입니다.
// id는 src/utils/hexagon-image.ts의 getHexagonImageIndex 결과와 동일한 1~36 인덱스입니다.
import { FITNESS_TYPE } from "@/types/hex";

export interface FitnessMbtiEntry {
  id: number;
  strongest: FITNESS_TYPE;
  strongestLabel: string;
  weakest: FITNESS_TYPE;
  weakestLabel: string;
  animalName: string;
  animalDescription: string;
  animalDescriptionBullets: string[];
}

export const FITNESS_MBTI_LIST: FitnessMbtiEntry[] = [
  {
    id: 1,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "파워히어로 곰 🐻",
    animalDescription: "한 방은 강하지만 지구력은 없어요",
    animalDescriptionBullets: [
      "한 방에 엄청난 힘을 발휘하지만 5분만 버티면 탈진하는 순간 파워 곰.",
      "무거운 걸 들어올리는 건 자신 있지만, 플랭크 1분은 고문이랍니다.",
      "가벼운 무게로 반복 횟수를 늘려가며 지구력을 키워보세요!",
    ],
  },
  {
    id: 2,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "숨찬 고릴라 🦍",
    animalDescription: "힘은 세지만 조금만 움직여도 헥헥거려요",
    animalDescriptionBullets: [
      "헬스장에서 무거운 바벨을 번쩍 들어올리지만, 계단 3층만 올라가도 숨이 턱까지 차오르는 숨찬 고릴라.",
      "힘은 세지만 오래 움직이는 건 약점이에요.",
      "가벼운 조깅으로 심폐 지구력을 키워보는 건 어때요?",
    ],
  },
  {
    id: 3,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "중량치는 뻣뻣 코끼리 🐘",
    animalDescription: "힘은 엄청난데 몸이 뻣뻣해요",
    animalDescriptionBullets: [
      "중량 운동에서는 최강이지만 스트레칭만 하면 비명이 나오는 뻣뻣한 코끼리.",
      "힘은 엄청나지만 몸은 나무판자처럼 뻣뻣해요.",
      "운동 전후 5분 스트레칭으로 유연성을 조금씩 키워보세요!",
    ],
  },
  {
    id: 4,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "느긋한 들소 🐃",
    animalDescription: "무게는 버티지만 반응이 느려요",
    animalDescriptionBullets: [
      "묵직한 힘으로 무거운 걸 버티지만 빠른 반응이 필요하면 당황하는 느린 들소.",
      "천천히 움직이는 건 좋지만 순간 반응은 약해요.",
      "가벼운 민첩성 훈련으로 반응 속도를 올려보는 건 어떨까요?",
    ],
  },
  {
    id: 5,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "우직한 걸음걸이 하마 🦛",
    animalDescription: "힘은 세지만 재빠르게 못 움직여요",
    animalDescriptionBullets: [
      "엄청난 힘으로 밀어붙이지만 방향 전환은 서툰 묵직한 하마.",
      "직진은 강하지만 재빠른 움직임은 약점이에요.",
      "좌우 스텝 연습으로 민첩성을 키워보세요!",
    ],
  },
  {
    id: 6,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "끈기가득 다람쥐 🐿️",
    animalDescription: "오래 버티지만 순간 파워는 약해요",
    animalDescriptionBullets: [
      "끈기 있게 오래오래 버티지만 순간 파워는 약한 끈기 다람쥐.",
      "플랭크 3분도 거뜬하지만 무거운 건 못 들어요.",
      "가벼운 덤벨로 근력 운동을 시작해보는 건 어떨까요?",
    ],
  },
  {
    id: 7,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "복근짱짱 개미 🐜",
    animalDescription: "버티기는 잘하는데 달리기는 힘들어요",
    animalDescriptionBullets: [
      "복근 운동은 100개도 가능하지만 달리기만 시작하면 금방 지치는 플랭크 개미.",
      "버티기는 최고지만 심폐는 약해요.",
      "가벼운 유산소 운동으로 심폐 지구력을 키워보세요!",
    ],
  },
  {
    id: 8,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "양철로봇 일개미 🐜",
    animalDescription: "열심히 일하지만 몸이 경직돼있어요",
    animalDescriptionBullets: [
      "플랭크 5분도 끄떡없지만 앞으로 몸 숙이기는 고문인 뻣뻣 일개미.",
      "버티는 힘은 최강이지만 몸은 나무처럼 뻣뻣해요.",
      "매일 5분 스트레칭으로 유연성을 조금씩 개선해보세요!",
    ],
  },
  {
    id: 9,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "한 발 느린 비버 🦫",
    animalDescription: "꾸준히 일하지만 반응은 느려요",
    animalDescriptionBullets: [
      "꾸준히 오래 버티는 건 잘하지만 빠른 반응은 어려운 느긋한 비버.",
      "끈기는 최고지만 순간 반응은 느려요.",
      "반응 속도 게임으로 재미있게 순발력을 키워보세요!",
    ],
  },
  {
    id: 10,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "오래오래 걷는 두더지 🦔",
    animalDescription: "끈기는 있지만 민첩하진 않아요",
    animalDescriptionBullets: [
      "묵묵히 오래 버티는 건 잘하지만 재빠른 움직임은 서툰 묵묵한 두더지.",
      "끈기는 있지만 민첩성은 약해요.",
      "좌우 이동 연습으로 민첩성을 키워보는 건 어떨까요?",
    ],
  },
  {
    id: 11,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "마라톤 끝판왕 사슴 🦌",
    animalDescription: "끝없이 달리지만 힘은 약해요",
    animalDescriptionBullets: [
      "끝없이 달릴 수 있지만 무거운 물건만 보면 피하는 마라톤 사슴.",
      "지구력은 최고지만 힘은 약해요.",
      "가벼운 근력 운동으로 균형을 맞춰보세요!",
    ],
  },
  {
    id: 12,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "유산소만랩 토끼 🐰",
    animalDescription: "달리기는 잘하지만 버티기는 못해요",
    animalDescriptionBullets: [
      "달리기는 끝도 없이 잘하지만 윗몸일으키기 10개면 포기하는 유산소 토끼.",
      "심폐는 최강이지만 근지구력은 약해요.",
      "코어 운동으로 버티는 힘을 키워보세요!",
    ],
  },
  {
    id: 13,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "낭만여행가 뻣뻣 늑대 🐺",
    animalDescription: "오래 달리지만 몸이 뻣뻣해요",
    animalDescriptionBullets: [
      "10km를 거뜬히 달리지만 신발 끈 묶으려 허리 숙이면 비명이 나오는 뻣뻣 러너 공주.",
      "달리기 후엔 꼭 스트레칭을 해야 하지만 늘 까먹는답니다.",
      "오늘부터 5분만 스트레칭 루틴을 만들어보세요!",
    ],
  },
  {
    id: 14,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "반응느린 능글여우 🦊",
    animalDescription: "장거리는 좋지만 순간 반응은 느려요",
    animalDescriptionBullets: [
      "마라톤은 완주하지만 100m 전력질주는 힘든 느긋한 여우.",
      "장거리는 강하지만 순간 반응은 느려요.",
      "짧은 거리 스프린트로 순발력을 키워보세요!",
    ],
  },
  {
    id: 15,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "당근에게 일편단심 말 🐴",
    animalDescription: "앞으로 달리기는 잘하지만 방향 전환은 서툴러요",
    animalDescriptionBullets: [
      "앞으로만 달리는 건 최고지만 지그재그는 어려운 직진 말.",
      "직선 코스는 강하지만 방향 전환은 약해요.",
      "콘 드리블 연습으로 민첩성을 키워보는 건 어떨까요?",
    ],
  },
  {
    id: 16,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "말랑말랑 문어 🐙",
    animalDescription: "말랑말랑하지만 힘이 없어요",
    animalDescriptionBullets: [
      "몸은 부드럽게 휘어지지만 무거운 물건만 보면 도망가는 고무줄 공주.",
      "요가 매트 위에서는 여왕이지만, 장바구니 들기는 여전히 숙제랍니다.",
      "가벼운 덤벨로 천천히 시작해보는 건 어떨까요?",
    ],
  },
  {
    id: 17,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "5분 요가 뱀 🐍",
    animalDescription: "유연하지만 오래 버티진 못해요",
    animalDescriptionBullets: [
      "요가 자세는 완벽하게 잡지만 5분만 버티면 포기하는 5분 뱀.",
      "유연성은 최고지만 버티는 힘은 약해요.",
      "자세 유지 시간을 조금씩 늘려보세요!",
    ],
  },
  {
    id: 18,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "숨찬 유연 고양이 🐱",
    animalDescription: "유연한데 조금만 뛰어도 힘들어요",
    animalDescriptionBullets: [
      "개다리 찢기는 완벽하지만 계단만 올라가도 숨차는 숨찬 고양이.",
      "스트레칭은 최고지만 유산소는 약해요.",
      "가벼운 산책으로 심폐 지구력을 키워보세요!",
    ],
  },
  {
    id: 19,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "느긋한 젠틀 표범 🐆",
    animalDescription: "몸은 유연한데 반응이 느려요",
    animalDescriptionBullets: [
      "몸은 부드럽게 휘어지지만 빠르게 반응하는 건 귀찮아하는 느긋한 고양이 공주.",
      "스트레칭 타임에는 완벽하지만 반사 게임에서는 꼴찌랍니다.",
      "가벼운 민첩성 운동으로 반응 속도를 올려보는 건 어떨까요?",
    ],
  },
  {
    id: 20,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "발레하는 팬더 🐼",
    animalDescription: "유연하지만 민첩하진 않아요",
    animalDescriptionBullets: [
      "어떤 자세든 완벽하게 구부리지만 빠르게 움직이는 건 싫어하는 슬로우 팬더.",
      "유연성은 완벽하지만 민첩성은 약해요.",
      "스텝 운동으로 재빠른 움직임을 연습해보세요!",
    ],
  },
  {
    id: 21,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "번개비행 참새 🐦",
    animalDescription: "반응은 빠르지만 힘이 약해요",
    animalDescriptionBullets: [
      "0.1초 만에 반응하지만 무거운 건 못 드는 번개 참새.",
      "순간 반응은 최고지만 힘은 약해요.",
      "가벼운 근력 운동으로 파워를 키워보세요!",
    ],
  },
  {
    id: 22,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "전력질주 치타 🐆",
    animalDescription: "순간 스피드는 최고지만 금방 지쳐요",
    animalDescriptionBullets: [
      "출발선에서는 모두를 앞서지만 100m만 달리면 금방 지쳐버리는 단거리 치타.",
      "순간의 스피드는 최고지만 긴 호흡이 필요한 순간엔 약해요.",
      "짧은 거리를 여러 번 반복하는 인터벌 훈련으로 지구력을 키워보세요!",
    ],
  },
  {
    id: 23,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "낚아채는 독수리 🦅",
    animalDescription: "처음 반응은 빠른데 오래 못 가요",
    animalDescriptionBullets: [
      "처음 5초는 번개처럼 빠르지만 그 뒤로는 지쳐버리는 5초 독수리.",
      "순간 스피드는 최고지만 오래 못 가요.",
      "유산소 운동으로 스태미나를 키워보세요!",
    ],
  },
  {
    id: 24,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "부딪히는 매 🦅",
    animalDescription: "빠르지만 몸이 뻣뻣해요",
    animalDescriptionBullets: [
      "빠르게 질주하지만 몸 숙이기는 고문인 뻣뻣 매.",
      "순발력은 최고지만 유연성은 약해요c",
    ],
  },
  {
    id: 25,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "직진 콘도르 🦅",
    animalDescription: "직선 비행은 빠른데 방향 전환은 느려요",
    animalDescriptionBullets: [
      "직선으로 날아가는 건 빠르지만 방향 전환은 느린 직진 콘도르.",
      "순발력은 최고지만 민첩성은 약해요.",
      "지그재그 달리기로 방향 전환 능력을 키워보세요!",
    ],
  },
  {
    id: 26,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "하늘하늘 나비 🦋",
    animalDescription: "재빠르지만 힘이 없어요",
    animalDescriptionBullets: [
      "재빠르게 이리저리 움직이지만 힘은 약한 나비 공주.",
      "민첩성은 최고지만 무거운 건 못 들어요.",
      "가벼운 근력 운동으로 파워를 더해보세요!",
    ],
  },
  {
    id: 27,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "쏜살 벌새 🐦",
    animalDescription: "민첩하지만 금방 지쳐요",
    animalDescriptionBullets: [
      "처음엔 재빠르게 움직이지만 5분만 지나면 지치는 5분 벌새.",
      "민첩성은 최고지만 버티는 힘은 약해요.",
      "인터벌 훈련으로 지구력을 키워보세요!",
    ],
  },
  {
    id: 28,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "의지박약 다람쥐 🐿️",
    animalDescription: "재빠르게 움직이지만 오래 못해요",
    animalDescriptionBullets: [
      "재빠르게 이리저리 움직이지만 금방 숨차는 숨찬 다람쥐.",
      "민첩성은 최고지만 심폐는 약해요.",
      "가벼운 유산소로 스태미나를 키워보세요!",
    ],
  },
  {
    id: 29,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "뻣뻣 족제비 🦡",
    animalDescription: "민첩한데 몸이 경직돼있어요",
    animalDescriptionBullets: [
      "빠르게 방향 전환하지만 몸은 뻣뻣한 뻣뻣 족제비.",
      "민첩성은 최고지만 유연성은 약해요.",
      "동적 스트레칭으로 유연성을 개선해보세요!",
    ],
  },
  {
    id: 30,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "지그재그 원숭이 🐒",
    animalDescription: "방향 전환은 잘하는데 반응은 느려요",
    animalDescriptionBullets: [
      "좌우로 방향 전환은 잘하지만 순간 반응은 느린 지그재그 원숭이.",
      "민첩성은 최고지만 순발력은 약해요.",
      "반응 속도 훈련으로 순발력을 키워보세요!",
    ],
  },
  {
    id: 31,
    strongest: "STRENGTH",
    strongestLabel: "근력",
    weakest: "STRENGTH",
    weakestLabel: "근력",
    animalName: "완벽주의 사자 🦁",
    animalDescription: "모든 면에서 힘이 넘치는 만능 동물이에요",
    animalDescriptionBullets: [
      "모든 면에서 힘이 넘치는 완벽한 사자 공주.",
      "근력도, 근지구력도, 모든 게 완벽해요.",
      "지금의 컨디션을 유지하면서 다른 체력 요소도 균형있게 발전시켜보세요!",
    ],
  },
  {
    id: 32,
    strongest: "ENDURANCE",
    strongestLabel: "근지구력",
    weakest: "ENDURANCE",
    weakestLabel: "근지구력",
    animalName: "끝없는 음유시인 낙타 🐫",
    animalDescription: "사막을 횡단하는 지칠 줄 모르는 동물이에요",
    animalDescriptionBullets: [
      "지치지 않고 끝없이 버틸 수 있는 끝없는 낙타.",
      "사막도 횡단하는 무한 지구력의 소유자예요.",
      "이제 다른 체력 요소도 골고루 키워서 완벽한 밸런스를 만들어보세요!",
    ],
  },
  {
    id: 33,
    strongest: "CARDIO",
    strongestLabel: "심폐지구력",
    weakest: "CARDIO",
    weakestLabel: "심폐지구력",
    animalName: "무한방랑자 늑대 🐺",
    animalDescription: "끝없이 달릴 수 있는 스태미나의 왕이에요",
    animalDescriptionBullets: [
      "숨이 차는 걸 모르는 심폐 최강 무한 늑대.",
      "끝없이 달릴 수 있는 스태미나의 왕이에요.",
      "이제 근력과 유연성도 함께 발전시켜 완벽한 몸을 만들어보세요!",
    ],
  },
  {
    id: 34,
    strongest: "FLEXIBILITY",
    strongestLabel: "유연성",
    weakest: "FLEXIBILITY",
    weakestLabel: "유연성",
    animalName: "흐르는 우아 고양이 🐱",
    animalDescription: "어떤 자세도 가능한 유연함의 끝판왕이에요",
    animalDescriptionBullets: [
      "몸의 모든 관절이 자유로운 요가의 여왕 완벽한 고양이.",
      "어떤 자세도 완벽하게 소화해요.",
      "이제 근력과 심폐 지구력도 함께 키워서 진정한 올라운더가 되어보세요!",
    ],
  },
  {
    id: 35,
    strongest: "QUICKNESS",
    strongestLabel: "순발력",
    weakest: "QUICKNESS",
    weakestLabel: "순발력",
    animalName: "우사인볼트 치타 🐆",
    animalDescription: "순간 스피드로는 누구도 따라올 수 없어요",
    animalDescriptionBullets: [
      "0.1초의 반응속도로 움직이는 번개 같은 최고 치타.",
      "순간 스피드로는 누구도 따라올 수 없어요.",
      "이제 지구력도 함께 키워서 오래 달리는 치타가 되어보세요!",
    ],
  },
  {
    id: 36,
    strongest: "AGILITY",
    strongestLabel: "민첩성",
    weakest: "AGILITY",
    weakestLabel: "민첩성",
    animalName: "금메달 클라이머 원숭이 🐵",
    animalDescription: "나무에서 자유롭게 날아다니는 민첩함의 달인이에요",
    animalDescriptionBullets: [
      "어떤 방향으로도 자유자재로 움직이는 완벽한 원숭이.",
      "나무에서 날아다니는 민첩함의 달인이에요.",
      "이제 근력과 지구력도 함께 발전시켜 완벽한 몸을 만들어보세요!",
    ],
  },
];

export function getFitnessMbtiById(id: number): FitnessMbtiEntry {
  const entry = FITNESS_MBTI_LIST.find((e) => e.id === id);
  if (!entry) {
    throw new Error(`Unknown fitness mbti id: ${id}`);
  }
  return entry;
}
